services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "23731497"
    ports:
      - "3307:3306"
    volumes:
      - ~/Documents/mysql:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
